AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: KC Authorizer Microservice

Parameters:
  EnvironmentId:
    Type: String
    Description: Environment ID

  AuthorizerAlias:
    Type: String
    Description: Authorizer Lambda Alias

Resources:
  AuthenticationInfrastructure:
    Type: AWS::Serverless::Application
    Properties:
      Location: kc-authentication-app/auth-template.yaml
      Parameters:
        EnvironmentId: !Ref EnvironmentId
        AuthorizerAlias: !Ref AuthorizerAlias