AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: KC Authorizer Microservice

Parameters:
  EnvironmentId:
    Type: String
    Description: Environment ID

  AuthorizerAlias:
    Type: String
    Description: Authorizer Lambda Alias

  LogRetentionInDays:
    Type: String
    Description: Number of days to retain logs

  AuthAwsRegion:
    Type: String
    Description: AWS Region where the Auth stack is deployed

  AuthClientId:
    Type: String
    Description: Auth Client ID
  
  AuthSecretClient:
    Type: String
    Description: Auth Secret Client

  AuthUserPoolId:
    Type: String
    Description: Auth User Pool ID

Resources:
  AuthenticationInfrastructure:
    Type: AWS::Serverless::Application
    Properties:
      Location: kc-authentication-app/auth-template.yaml
      Parameters:
        EnvironmentId: !Ref EnvironmentId
        AuthorizerAlias: !Ref AuthorizerAlias
        LogRetentionInDays: !Ref LogRetentionInDays
        AuthAwsRegion: !Ref AuthAwsRegion
        AuthClientId: !Ref AuthClientId
        AuthSecretClient: !Ref AuthSecretClient
        AuthUserPoolId: !Ref AuthUserPoolId